export const mockUserSetings = [
    {
        userId: 1,
        receiveNotifications: true,
        receiveEmails: false,
        language: 'en',
        timezone: 'UTC',
        darkMode: true,
    },
    {
        userId: 2,
        receiveNotifications: false,
        receiveEmails: true,
        language: 'es',
        timezone: 'CET',
        darkMode: false,
    },
    {
        userId: 3,
        receiveNotifications: true,
        receiveEmails: true,
        language: 'fr',
        timezone: 'PST',
        darkMode: true,
    },
    {
        userId: 4,
        receiveNotifications: false,
        receiveEmails: false,
        language: 'de',
        timezone: 'EST',
        darkMode: false,
    },
    {
        userId: 5,
        receiveNotifications: true,
        receiveEmails: true,
        language: 'it',
        timezone: 'GMT',
        darkMode: true,
    },
    {
        userId: 6,
        receiveNotifications: false,
        receiveEmails: true,
        language: 'pt',
        timezone: 'BST',
        darkMode: false,
    },
    {
        userId: 7,
        receiveNotifications: true,
        receiveEmails: false,
        language: 'ru',
        timezone: null,
        darkMode: true,
    },
    {
        userId: 8,
        receiveNotifications: false,
        receiveEmails: true,
        language: 'zh',
        darkMode: false,
    },
    {
        userId: 9,
        receiveNotifications: true,
        receiveEmails: false,
        language: 'ja',
        timezone: 'JST',
        darkMode: true,
    },
    {
        userId: 10,
        receiveNotifications: false,
        receiveEmails: true,
        language: 'ko',
        timezone: 'KST',
        darkMode: false,
    }
];